import { StyleSheet } from "react-native";
import { colors as c } from "../theme/colors";
export const ui = StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.background },
  shell: { flex: 1, width: "100%", maxWidth: 520, alignSelf: "center" },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderColor: c.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brand: { color: c.text, fontSize: 24, fontWeight: "700", letterSpacing: -1 },
  tag: { color: c.accent, fontSize: 10, letterSpacing: 1 },
  content: { padding: 20, gap: 16, paddingBottom: 28 },
  title: {
    color: c.text,
    fontSize: 29,
    fontWeight: "600",
    letterSpacing: -0.7,
  },
  body: { color: c.muted, fontSize: 14, lineHeight: 23 },
  small: { color: c.muted, fontSize: 11, lineHeight: 18 },
  card: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    gap: 10,
  },
  cardTitle: { fontSize: 17, fontWeight: "600", color: c.text },
  row: { flexDirection: "row", gap: 8, alignItems: "center", flexWrap: "wrap" },
  button: {
    paddingHorizontal: 17,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: c.accent,
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  secondary: {
    backgroundColor: c.elevated,
    borderWidth: 1,
    borderColor: c.border,
  },
  buttonText: { color: c.background, fontWeight: "600", fontSize: 13 },
  secondaryText: { color: c.text },
  input: {
    backgroundColor: c.surface,
    color: c.text,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: 16,
    padding: 15,
    fontSize: 15,
    minHeight: 50,
  },
  nav: {
    flexDirection: "row",
    padding: 8,
    borderTopWidth: 1,
    borderColor: c.border,
    gap: 4,
  },
  navItem: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: "center",
  },
  selected: { backgroundColor: c.elevated },
  navText: { color: c.muted, fontSize: 11, fontWeight: "600" },
  selectedText: { color: c.accent },
  divider: { height: 1, backgroundColor: c.border },
  banner: {
    backgroundColor: c.surface,
    paddingHorizontal: 20,
    paddingVertical: 7,
  },
  error: { color: c.danger, fontSize: 13, lineHeight: 21 },
});
